Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
spots = load_sunspots()
plt.plot(spots)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_16501/3762959344.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mspots[0m [0;34m=[0m [0mload_sunspots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mspots[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_16501/3116410217.py[0m in [0;36mload_sunspots[0;34m()[0m
[1;32m     12[0m     [0mdata[0m [0;34m=[0m [0mcsv[0m[0;34m.[0m[0mreader[0m[0;34m([0m[0mStringIO[0m[0;34m([0m[0mx[0m[0;34m.[0m[0mtext[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m     [0mnext[0m[0;34m([0m[0mdata[0m[0;34m)[0m  [0;31m# Skip header row[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m     [0;32mreturn[0m [0;34m[[0m[0mfloat[0m[0;34m([0m[0mrow[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m)[0m [0;32mfor[0m [0mrow[0m [0;32min[0m [0mdata[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_16501/3116410217.py[0m in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m     12[0m     [0mdata[0m [0;34m=[0m [0mcsv[0m[0;34m.[0m[0mreader[0m[0;34m([0m[0mStringIO[0m[0;34m([0m[0mx[0m[0;34m.[0m[0mtext[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m     [0mnext[0m[0;34m([0m[0mdata[0m[0;34m)[0m  [0;31m# Skip header row[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m     [0;32mreturn[0m [0;34m[[0m[0mfloat[0m[0;34m([0m[0mrow[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m)[0m [0;32mfor[0m [0mrow[0m [0;32min[0m [0mdata[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mValueError[0m: could not convert string to float: 'You have exceeded the anonymous user limit of 50 calls per day. To make more calls today, please register for a free Nasdaq Data Link account and then include your API key with your requests.'
ValueError: could not convert string to float: 'You have exceeded the anonymous user limit of 50 calls per day. To make more calls today, please register for a free Nasdaq Data Link account and then include your API key with your requests.'

